name: Gigaspace XAP Documentation Portal
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
encoding: UTF-8

latest_xap_release: "9.7"
latest_xap_version: "9.7.0"
latest_maven_version: "9.6.2-9900-RELEASE"
latest_build_filename: "gigaspaces-xap-premium-9.6.2-ga-b9900.zip"
latest_gshome_dirname: "gigaspaces-xap-premium-9.7.0-ga"
latest_default_lookup_group: "gigaspaces-9.7.0-XAPPremium-ga"
latest_java_url: "/xap97"
latest_net_url: "/xap97net"

latest_cloudify_release: "2.6"

base_javadoc_url: "http://www.gigaspaces.com/docs/JavaDoc%{version}/index.html?%{fqcn}.html"
base_scaladoc_url: "http://www.gigaspaces.com/docs/scaladocs%{version}/#%{fqcn}"
base_dotnetdoc_url: "http://www.gigaspaces.com/docs/dotnetdocs%{version}/html/T_%{fqcn}.htm"

categories-list: ["SBP", "XAP97", "XAP97NET", "XAP97ADM",  "XAP97INST", "PRODUCT_OVERVIEW", "API_DOCUMENTATION", "EARLY_ACCESS", "HOWTO" , "FAQ" ,"RELEASE_NOTES" ,"TUTORIALS" ]
